
export const metadata = {
  title: 'Hồ Sơ Donor',
  description: 'Generated by Hỏi dân it',
}

export default function RootLayout({
  children,
}:{
    children: React.ReactNode
  }) 
{
  return (
    <>
        {children}
    </>
  )
}
